# Generated by Django 5.1.2 on 2024-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowerresponse",
            name="response_text",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanquestion",
            name="has_options",
            field=models.BooleanField(default=False),
        ),
    ]
