# Generated by Django 5.1.2 on 2024-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_loan", "0003_loanquestion_response_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanquestion",
            name="response_type",
            field=models.CharField(
                blank=True,
                choices=[("string", "String"), ("integer", "Integer")],
                default="integer",
                max_length=10,
                null=True,
            ),
        ),
    ]
