# Generated by Django 5.1.2 on 2024-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_loan", "0004_alter_loanquestion_response_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowerresponse",
            name="response_text",
            field=models.IntegerField(),
        ),
    ]
