# Generated by Django 5.1.2 on 2024-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_loan", "0005_alter_borrowerresponse_response_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanquestion",
            name="response_type",
        ),
        migrations.AlterField(
            model_name="borrowerresponse",
            name="response_text",
            field=models.PositiveBigIntegerField(),
        ),
    ]
