# Generated by Django 5.1.2 on 2024-10-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_loan", "0006_remove_loanquestion_response_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowerresponse",
            name="selected_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="car_loan.loanquestionoptions",
            ),
        ),
    ]
